### PR TITLE
Windows Docker and Tailwind watch mode

### LINKED ISSUE #56: Windows Docker and Tailwind watch mode
The watch mode on my project was not working.

I managed to get the watch mode working by adding `--poll` to the tailwind command.

For reference : https://github.com/tailwindlabs/tailwindcss/discussions/8100

Can we add a `--poll` option to the command, or is there another way to do it ?

### PR DESCRIPTION
**Pull request by Mitraniom**
Closes #56

### CODE REVIEW

**Review by bocharsky-bw — CHANGES_REQUESTED** [review]
I think we should repeat the same behavior like Tailwind does, i.e. `--watch` and `--poll` should be 2 separate options. IMO it would be better UX. You try the `--watch` first which will work in most cases, but if somehow it's not working for you - add that extra `--poll` option. First if all, it will be the same way as it's implemented upstream in Tailwind, so it will be intuitive, and second - it will avoid duplicating `--watch` when you run the command with `--watch --pollWatch` at the same time.

Could you refactor this please?

File: src/Command/TailwindBuildCommand.php [hunk 1]
```diff
@@ -33,6 +33,7 @@ protected function configure(): void
     {
         $this
             ->addOption('watch', 'w', null, 'Watch for changes and rebuild automatically')
+            ->addOption('poll', null, null, 'Apply --poll flag to the command')
```
Comment (bocharsky-bw) [inline src/Command/TailwindBuildCommand.php:36]: Let's be more descriptive on what it does, how about:
```suggestion
            ->addOption('poll', null, null, 'Use polling instead of filesystem events when watching')
```

File: src/TailwindBuilder.php [hunk 2]
```diff
@@ -48,12 +48,16 @@ public function __construct(
...
+        bool $poll,
         bool $minify,
     ): Process {
         $binary = $this->createBinary();
         $arguments = ['-c', $this->configPath, '-i', $this->inputPath, '-o', $this->getInternalOutputCssPath()];
         if ($watch) {
             $arguments[] = '--watch';
+            if ($poll) {
+                $arguments[] = '--poll';
+            }
```
Comment (bocharsky-bw) [inline src/TailwindBuilder.php:60]: Can't we use --poll without --watch? I see these fields are probably dependent, but this implementation will just silently not add --poll if no --watch was passed to the final command. But probably that's not a problem, because if you don't pass --watch then it's just finish the execution and that's it, so probably that's not a big deal to have this nested ot the --watch.

Just curious about your opinion on it

**Review by bocharsky-bw — APPROVED** [review]
This looks good to me now, thanks for adding more changes!

One minor question I would like to discuss... but I think we can even merge it as is

File: src/Command/TailwindBuildCommand.php (hunk 1 above)
Comment (Mitraniom) [reply src/Command/TailwindBuildCommand.php]: Indeed, your description is far more relevant

File: src/TailwindBuilder.php (hunk 2 above)
Comment (Mitraniom) [reply src/TailwindBuilder.php:60]: In my opinion, it should not be possible to use the `--poll` option if the `--watch` option is not called, maybe we should throw an exception if this case happens ?

Comment (bocharsky-bw) [reply src/TailwindBuilder.php:60]: Hm, that's not something that Tailwind does, so I think it's safe to merge it as is.

Thanks again!
