### PR TITLE
Tailwind v4 Support

### LINKED ISSUE #81: Watchman not found
Hey I used to begin my usual routine:

- ddev start
- and then the tailwind build watch command 

this is the output it generated me, additionally the tailwind classes doesn't apply anymore.

Image

What am I doing wrong?

### LINKED ISSUE #84: Only download tailwind binaries if none are present
TL; DR - Would you be open to a PR that makes `tailwind:build` update less aggressively?

I came to work today to a failing tailwind build. While investigating this problem,
I discovered that my `./var/tailwind` directory contained at least 4 different versions of
the tailwind binary, which I presume means that this bundle always looks for and downloads the latest version
of tailwind when running `console tailwind:build`. 

While I understand that not everyone likes to be chained to strictly pinned dependencies (praise be to [Nix](https://nixos.org/)), I think that it would be a more sensible default to check if there is any version
of tailwind already downloaded, and if so, only download a different one if a pinned version has been configured, and none of the downloaded versions match the configuration.

Suddenly updating users to a major revision without any notice is a bit jarring.

Let me know if this sounds good to you, and **thank you** for letting us pin a specific version.

Below is some pseudo code of what I'm thinking:

```php
<?php

/**
  * Downloads tailwind if necessary.
  * @return The version of binary that will be used.
  * /
function maybe_download_tailwindss($user_config): string {
    $downloaded_versions = find_downloaded_tailwind_binaries();
    $pinned_version = $user_config->binary_version;

    if ($pinned_version) {  
        if (in_array($pinned_version, $downloaded_versions)) {
            return $pinned_version;
        } else {
            return download_tailwind($pinned_version);
        }
    } else {
        if (empty($downloaded_versions)) {
            return download_tailwind('latest');
        } else {
            // Here you could check if a newer version exists upstream and inform the user.

            return end($downloaded_versions); // assuming versions are sorted in ascending order.
        }
    }
}

### PR DESCRIPTION
**Pull request by kbond**
- [x] require `binary` or `binary_version` be configured
- [x] normalize `binary_version` (1.2.3 => v1.2.3)
- [x] determine version from binary
- [x] `tailwind:build` v4 compatible
- [x] `tailwind:init` v4 compatible
- [x] docs
- [x] [Investigate the different binaries made available in v4+](https://github.com/SymfonyCasts/tailwind-bundle/pull/91#issuecomment-2698000585)
- [x] Recipe with pre-set version: https://github.com/symfony/recipes/pull/1383

Closes #86
Closes #87
Fixes #84
Fixes #81

### CODE REVIEW

File: src/DependencyInjection/TailwindExtension.php [hunk 1]
```diff
@@ -70,7 +70,13 @@ public function getConfigTreeBuilder(): TreeBuilder
                 ->end()
                 ->scalarNode('binary_version')
                     ->info('Tailwind CLI version to download - null means the latest version')
-                    ->defaultValue('v3.4.17')
+                    ->defaultNull()
+                    ->beforeNormalization()
+                        ->ifString()
+                        ->then(static function (string $version): string {
+                            return 'v'.ltrim($version, 'vV');
```
Comment (weaverryan) [inline src/DependencyInjection/TailwindExtension.php:77]: Can I use something simple like v4? Like with Composer, I don't want to be bothered with exact versions

**Review by weaverryan — APPROVED** [review]

File: src/DependencyInjection/TailwindExtension.php (hunk 1 above)
Comment (weaverryan) [reply src/DependencyInjection/TailwindExtension.php:77]: This is probably also important so we don't need to constantky update the recipe

Comment (kbond) [reply src/DependencyInjection/TailwindExtension.php:77]: I think it's important this be a "locked" version so all developers are using the same binary (there's a few issues about this).

If we allow composer-style versioning, we'd need a separate thing to "lock" it, which means an update command. I don't know we want to go down this road.

If anything, we could provide an update command that updates this value in config to the latest version:

- `tailwind:update`: updates from say 3.4.1 to latest 3.x
- `tailwind:update --major`: updates from say 3.4.1 to true latest

Comment (weaverryan) [reply src/DependencyInjection/TailwindExtension.php:77]: > I think it's important this be a "locked" version so all developers are using the same binary (there's a few issues about this).

You could opt into a lock by specifying the exact version, but everyone else could specify just 4 or 4.1

**Review by bocharsky-bw — APPROVED** [review]
Looks solid to me

**Comment by davidnectarestudio** [comment]
is there a planned release date about this feature? I'm working on a new project that customer requires TailwindCSS v4, can I do something to enable v4 meanwhile?

**Comment by kbond** [comment]
> is there a planned release date about this feature

I'm planning to finalize/release in the next day or so.

**Comment by kbond** [comment]
Regarding "Investigate the different binaries made available in v4+": The following existing OS/arch conditions have no equivalent in Tailwind v4:
- Linux + armv7
- Windows + arm64

It's possible the other v4 binaries work for these conditions but I'm going to wait until it's reported so we can verify.
